# Generated by Django 4.2.7 on 2023-11-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CSE", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sudent",
            new_name="Student",
        ),
    ]
